included:
  - NewProjectDemo

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods/*

disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name
  - nesting
  - cyclomatic_complexity
  - function_body_length
  - function_parameter_count